name: cicd

on:
  pull_request:
  push:
    branches:
      - '**'
  release:
    types: [published]

env:
  TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
  TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:

  build_linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        image:
        - quay.io/pypa/manylinux2014_x86_64
        python: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: . tools/cicd/linux/bootstrap.sh ${{ matrix.python }}
    - name: analyse
      run: . tools/cicd/linux/analyse.sh
    - name: build
      run: . tools/cicd/linux/build.sh
    - name: test
      run: . tools/cicd/linux/test.sh
    - name: publish
      if: github.event_name == 'release'
      run: . tools/cicd/linux/publish.sh

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: . tools/cicd/macos/bootstrap.sh ${{ matrix.python }}
    - name: analyse
      run: . tools/cicd/macos/analyse.sh
    - name: build
      run: . tools/cicd/macos/build.sh
    - name: test
      run: . tools/cicd/macos/test.sh
    - name: publish
      if: github.event_name == 'release'
      run: . tools/cicd/macos/publish.sh
